"""
Shared contact-localisation heuristics.

This pack holds the generic baseline that applies when no country-specific
override exists. Country packs should add only genuinely local vocabulary on
top of these defaults.
"""

DEFAULT_DISCOVERY_PACK = {
    "generic_branch_segments": [],
    "branch_root_segments": [
        "offices",
        "services",
    ],
    "hreflang_preferences": [],
    "high_yield_seed_patterns": [
        "contact",
        "directory",
        "exchange",
        "global",
        "international",
        "international-office",
        "mobility",
        "partnership",
        "people",
        "staff",
        "study-abroad",
        "team",
    ],
}


DEFAULT_CONTACT_PACK = {
    "name_particles": [
        "abu",
        "al",
        "ap",
        "ben",
        "bin",
        "bint",
        "da",
        "das",
        "de",
        "del",
        "der",
        "des",
        "dos",
        "du",
        "el",
        "ibn",
        "la",
        "le",
        "mac",
        "mc",
        "st",
        "st.",
        "van",
        "von",
    ],
    "name_stopwords": [
        "address",
        "admissions",
        "administrative",
        "area",
        "avenue",
        "building",
        "call",
        "campus",
        "center",
        "centre",
        "city",
        "contact",
        "contacts",
        "department",
        "director",
        "directory",
        "email",
        "floor",
        "global",
        "hello",
        "international",
        "mail",
        "manager",
        "mobility",
        "office",
        "partnership",
        "partnerships",
        "phone",
        "policy",
        "public",
        "relations",
        "road",
        "room",
        "service",
        "services",
        "staff",
        "street",
        "student",
        "students",
        "support",
        "team",
        "title",
        "unit",
        "university",
        "welcome",
    ],
    "address_terms": [
        "address",
        "avenue",
        "building",
        "campus",
        "city",
        "floor",
        "road",
        "room",
        "street",
    ],
    "address_like_phrases": [],
    "office_name_terms": [
        "administration",
        "admissions",
        "campus",
        "center",
        "centre",
        "department",
        "desk",
        "division",
        "office",
        "policy",
        "program",
        "programme",
        "school",
        "secretariat",
        "service",
        "services",
        "staff",
        "team",
        "unit",
        "welcome",
    ],
    "boilerplate_name_fragments": [
        "click here",
        "contact us",
        "email us",
        "for more information",
        "international office",
        "office of",
        "privacy policy",
    ],
    "office_role_terms": [
        "admissions",
        "center",
        "centre",
        "cooperation",
        "department",
        "engagement",
        "erasmus",
        "exchange",
        "global",
        "helpdesk",
        "international",
        "mobility",
        "office",
        "partnership",
        "relations",
        "secretariat",
        "service",
        "study abroad",
        "team",
        "unit",
        "welcome",
    ],
    "role_signal_terms": [
        "global engagement",
        "international cooperation",
        "international relations",
        "international student",
        "international students",
        "mobility office",
        "study abroad",
        "welcome office",
    ],
    "role_aliases": {
        "global engagement": [
            "global engagement",
            "global office",
            "global strategy",
        ],
        "international admissions": [
            "international admission",
            "international admissions",
        ],
        "international mobility": [
            "erasmus",
            "exchange",
            "mobility",
        ],
        "international partnerships": [
            "cooperation",
            "partnership",
            "partnerships",
        ],
        "international relations": [
            "international relations",
        ],
        "international student office": [
            "international student",
            "international students",
            "welcome office",
        ],
    },
    "international_markers": [
        "global",
        "international",
    ],
    "office_markers": [
        "center",
        "centre",
        "department",
        "desk",
        "office",
        "secretariat",
        "service",
        "services",
        "team",
        "unit",
        "welcome",
    ],
    "admissions_markers": [
        "admission",
        "admissions",
    ],
    "relevant_mailbox_terms": [
        "cooperation",
        "engagement",
        "erasmus",
        "exchange",
        "global",
        "incoming",
        "international",
        "mobility",
        "outgoing",
        "partnership",
        "relations",
        "studyabroad",
        "studyabroadoffice",
    ],
    "irrelevant_mailbox_terms": [
        "housing",
        "library",
        "press",
        "privacy",
        "protocol",
        "student",
        "webmaster",
    ],
    "generic_unscoped_localparts": [
        "contact",
        "hello",
        "info",
        "office",
        "support",
    ],
    "suspicious_name_phrases": [
        "privacy policy",
    ],
    "suspicious_name_terms": [
        "academy",
        "college",
        "institute",
        "policy",
        "privacy",
        "university",
    ],
    "relevant_office_role_terms": [
        "erasmus",
        "exchange office",
        "global engagement",
        "international cooperation",
        "international office",
        "international partnerships",
        "international relations",
        "mobility office",
        "study abroad",
        "welcome office",
    ],
    "senior_role_terms": [
        "administrative director",
        "chair",
        "chancellor",
        "dean",
        "director",
        "executive director",
        "general director",
        "head",
        "manager",
        "president",
        "provost",
        "rector",
        "vice chancellor",
        "vice president",
        "vice rector",
    ],
    "international_leadership_terms": [
        "coordinator",
        "director of international",
        "global engagement lead",
        "head of international",
        "head of mobility",
        "head of partnerships",
        "international coordinator",
        "international delegate",
        "international director",
        "international lead",
        "mobility coordinator",
        "partnerships lead",
        "study abroad coordinator",
    ],
    "role_holder_page_terms": [
        "contact",
        "contacts",
        "directory",
        "governance",
        "leadership",
        "management",
        "office",
        "organization",
        "organisational",
        "organigram",
        "people",
        "staff",
        "team",
    ],
    "person_name_titles": [
        "dr",
        "mr",
        "mrs",
        "ms",
        "prof",
    ],
    "enrichment_block_phrases": [
        "european credit transfer system",
        "inter institutional agreement",
        "inter istitutional agreement",
        "inter-institutional agreement",
        "inter-istitutional agreement",
    ],
    "enrichment_block_terms": [
        "agreement",
        "credit",
        "credits",
        "info",
        "institutional",
        "istitutional",
        "magazine",
        "research",
        "study",
        "system",
    ],
}
