"""
France-specific discovery and contact vocabulary.

This pack is intentionally university-first for the current FYP focus. The
discovery terms are the high-value part; contact heuristics are kept modest and
only add genuinely French office/governance vocabulary.
"""

FRANCE_DISCOVERY_PACK = {
    "generic_branch_segments": [
        "page",
        "pages",
        "rubrique",
    ],
    "branch_root_segments": [
        "annuaire",
        "campus",
        "direction",
        "gouvernance",
        "international",
        "internationale",
        "organisation",
        "presidence",
        "service",
        "services",
        "vie-internationale",
    ],
    "high_yield_seed_patterns": [
        "affaires-internationales",
        "annuaire",
        "contacts",
        "cooperation-internationale",
        "erasmus",
        "gouvernance",
        "international",
        "internationale",
        "mobilite",
        "organigramme",
        "partenariats-internationaux",
        "personnel",
        "personnels",
        "relations-internationales",
    ],
    "tokens": [
        "affaires-internationales",
        "annuaire",
        "contacts",
        "cooperation",
        "cooperation-internationale",
        "direction",
        "direction-des-relations-internationales",
        "dri",
        "enseignants",
        "erasmus",
        "equipe",
        "gouvernance",
        "international",
        "internationale",
        "internationales",
        "mobilite",
        "mobilite-internationale",
        "organigramme",
        "partenariats",
        "partenariats-internationaux",
        "personnel",
        "personnels",
        "presidence",
        "relations-internationales",
        "service-des-relations-internationales",
        "vie-internationale",
    ],
    "anchor_terms": [
        "affaires internationales",
        "annuaire",
        "contacts",
        "coopération internationale",
        "cooperation internationale",
        "direction des relations internationales",
        "enseignants",
        "equipe",
        "équipe",
        "erasmus",
        "gouvernance",
        "international",
        "mobilite",
        "mobilité",
        "organigramme",
        "partenariats internationaux",
        "personnel",
        "personnels",
        "présidence",
        "presidence",
        "relations internationales",
        "service des relations internationales",
        "vie internationale",
    ],
    "cms_search_terms": [
        "affaires internationales",
        "annuaire",
        "contacts",
        "coopération internationale",
        "cooperation internationale",
        "direction des relations internationales",
        "erasmus",
        "gouvernance",
        "international",
        "mobilité internationale",
        "mobilite internationale",
        "organigramme",
        "partenariats internationaux",
        "personnel",
        "personnels",
        "présidence",
        "presidence",
        "relations internationales",
        "service des relations internationales",
        "vie internationale",
    ],
    "subdomains": [
        "dri",
        "international",
        "ri",
    ],
    "language_prefixes": ["fr", "en"],
    "hreflang_preferences": ["fr"],
    "directory_terms": [
        "annuaire",
        "equipe",
        "équipe",
        "enseignants",
        "personnel",
        "personnels",
        "trombinoscope",
    ],
    "governance_terms": [
        "direction",
        "gouvernance",
        "organigramme",
        "presidence",
        "présidence",
        "rectorat",
        "vice-presidence",
        "vice-présidence",
    ],
    "page_family_terms": {
        "contact": ["contact", "contacts", "nous-contacter"],
        "directory": [
            "annuaire",
            "equipe",
            "équipe",
            "enseignants",
            "personnel",
            "personnels",
            "trombinoscope",
        ],
        "office": [
            "bureau",
            "direction",
            "mission",
            "pole",
            "pôle",
            "service",
            "services",
        ],
        "governance": [
            "direction",
            "gouvernance",
            "organigramme",
            "presidence",
            "présidence",
            "rectorat",
            "vice-presidence",
            "vice-présidence",
        ],
        "international": [
            "affaires-internationales",
            "cooperation-internationale",
            "erasmus",
            "international",
            "internationale",
            "internationales",
            "mobilite",
            "mobilité",
            "partenariats-internationaux",
            "relations-internationales",
            "vie-internationale",
        ],
        "staff": [
            "equipe",
            "équipe",
            "enseignants",
            "personnel",
            "personnels",
            "team",
        ],
    },
    "negative_terms": [
        "actualites",
        "actualités",
        "agenda",
        "alumni",
        "archives",
        "blog",
        "evenements",
        "événements",
        "medias",
        "médias",
        "presse",
    ],
    "slug_hints": [
        "/affaires-internationales",
        "/annuaire",
        "/contacts",
        "/cooperation-internationale",
        "/direction-des-relations-internationales",
        "/erasmus",
        "/gouvernance",
        "/international",
        "/internationale",
        "/mobilite",
        "/mobilite-internationale",
        "/organigramme",
        "/partenariats-internationaux",
        "/personnel",
        "/personnels",
        "/presidence",
        "/relations-internationales",
        "/service-des-relations-internationales",
        "/vie-internationale",
        "/fr/affaires-internationales",
        "/fr/annuaire",
        "/fr/contacts",
        "/fr/cooperation-internationale",
        "/fr/erasmus",
        "/fr/gouvernance",
        "/fr/international",
        "/fr/mobilite",
        "/fr/organigramme",
        "/fr/personnels",
        "/fr/presidence",
        "/fr/relations-internationales",
        "/fr/vie-internationale",
    ],
}


FRANCE_CONTACT_PACK = {
    "name_particles": [
        "d",
        "d'",
        "de",
        "des",
        "du",
    ],
    "name_stopwords": [
        "accueil",
        "affaires",
        "annuaire",
        "bureau",
        "campus",
        "cedex",
        "contact",
        "direction",
        "ecole",
        "equipe",
        "gouvernance",
        "international",
        "internationale",
        "internationales",
        "mission",
        "mobilite",
        "organisation",
        "partenariats",
        "personnel",
        "personnels",
        "pole",
        "presidence",
        "relations",
        "service",
        "services",
        "universite",
    ],
    "address_terms": [
        "avenue",
        "batiment",
        "bâtiment",
        "boulevard",
        "campus",
        "cedex",
        "place",
        "quai",
        "rue",
    ],
    "office_name_terms": [
        "bureau",
        "direction",
        "mission",
        "pole",
        "pôle",
        "presidence",
        "présidence",
        "service",
        "services",
    ],
    "boilerplate_name_fragments": [
        "nous contacter",
        "plan du site",
        "relations internationales",
        "service des relations internationales",
    ],
    "office_role_terms": [
        "affaires",
        "bureau",
        "direction",
        "international",
        "internationale",
        "internationales",
        "mobilite",
        "partenariats",
        "relations",
        "service",
        "services",
    ],
    "role_signal_terms": [
        "affaires internationales",
        "cooperation internationale",
        "direction des relations internationales",
        "erasmus+",
        "mobilite internationale",
        "relations internationales",
        "service des relations internationales",
    ],
    "role_aliases": {
        "international office": [
            "affaires internationales",
            "direction des relations internationales",
            "service des relations internationales",
        ],
        "international mobility": [
            "erasmus",
            "mobilite internationale",
        ],
        "international partnerships": [
            "cooperation internationale",
            "partenariats internationaux",
        ],
        "international relations": [
            "relations internationales",
        ],
        "international student office": [
            "accueil international",
            "etudiants internationaux",
        ],
    },
    "international_markers": [
        "international",
        "internationale",
        "internationales",
        "mobilite",
    ],
    "office_markers": [
        "bureau",
        "direction",
        "mission",
        "pole",
        "pôle",
        "service",
    ],
    "admissions_markers": [
        "admission",
        "admissions",
        "candidature",
        "inscription",
    ],
    "relevant_mailbox_terms": [
        "cooperation",
        "dri",
        "erasmus",
        "international",
        "mobilite",
        "partenariats",
        "relations",
    ],
    "irrelevant_mailbox_terms": [
        "bibliotheque",
        "bibliothèque",
        "presse",
        "scolarite",
        "scolarité",
        "vie-etudiante",
        "webmaster",
    ],
    "suspicious_name_terms": [
        "annuaire",
        "bureau",
        "direction",
        "ecole",
        "gouvernance",
        "organisation",
        "personnel",
        "service",
        "universite",
    ],
    "relevant_office_role_terms": [
        "affaires internationales",
        "cooperation internationale",
        "direction des relations internationales",
        "mobilite internationale",
        "partenariats internationaux",
        "relations internationales",
        "service des relations internationales",
    ],
    "senior_role_terms": [
        "chef de service",
        "delegue",
        "délégué",
        "directeur",
        "directrice",
        "president",
        "président",
        "recteur",
        "responsable",
        "vice-president",
        "vice-président",
        "vice-recteur",
    ],
    "international_leadership_terms": [
        "charge des relations internationales",
        "chargé des relations internationales",
        "coordinatrice erasmus",
        "coordinateur erasmus",
        "directeur des relations internationales",
        "directrice des relations internationales",
        "responsable des relations internationales",
        "responsable mobilite internationale",
        "responsable mobilité internationale",
    ],
    "role_holder_page_terms": [
        "annuaire",
        "gouvernance",
        "organigramme",
        "personnel",
        "personnels",
        "presidence",
        "présidence",
        "relations internationales",
    ],
    "person_name_titles": [
        "dr",
        "m",
        "mme",
        "mr",
        "pr",
        "prof",
        "professeur",
        "professeure",
    ],
    "enrichment_block_phrases": [
        "plan du site",
        "vie etudiante",
    ],
    "enrichment_block_terms": [
        "agenda",
        "actualites",
        "actualités",
        "annuaire",
        "service",
    ],
}
