"""
Italy-specific discovery vocabulary.

This is deliberately focused on discovery and slug hints only.
"""

ITALY_DISCOVERY_PACK = {
    "generic_branch_segments": [
        "pagina",
        "pagina-strutturale",
    ],
    "branch_root_segments": [
        "strutture",
        "servizi",
        "uffici",
    ],
    "high_yield_seed_patterns": [
        "contatti",
        "rubrica",
        "erasmus",
        "mobilita",
        "internazionale",
        "relazioni-internazionali",
        "organigramma",
        "uffici",
    ],
    "tokens": [
        "contatti", "rubrica", "uffici", "ufficio", "segreteria",
        "organigramma", "personale", "docenti", "internazionale",
        "internazionali", "internazionalizzazione", "mobilita",
        "erasmus", "cooperazione", "relazioni-internazionali",
        "partenariati", "partnership", "scambi",
        "amministrazione-trasparente", "organizzazione", "dirigenti",
        "vertice", "organi-di-governo", "governo",
        "organi-di-indirizzo-politico-amministrativo",
        "incarichi-amministrativi-di-vertice",
        "opportunita",
    ],
    "anchor_terms": [
        "contatti",
        "rubrica",
        "uffici",
        "segreteria",
        "personale",
        "docenti",
        "organizzazione",
        "organigramma",
        "dirigenti",
        "vertice",
        "amministrazione trasparente",
        "internazionale",
        "mobilita",
        "erasmus",
        "relazioni internazionali",
    ],
    "cms_search_terms": [
        "contatti",
        "rubrica",
        "ufficio erasmus",
        "erasmus",
        "mobilita internazionale",
        "relazioni internazionali",
        "internazionalizzazione",
        "cooperazione internazionale",
        "personale",
        "organigramma",
        "amministrazione trasparente",
        "dirigenti",
        "vertice",
        "organizzazione",
    ],
    "subdomains": [
        "international",
        "erasmus",
        "mobilita",
        "internazionale",
    ],
    "language_prefixes": ["it", "en"],
    "directory_terms": [
        "rubrica",
        "personale",
        "docenti",
        "strutture",
        "ruoli",
    ],
    "governance_terms": [
        "amministrazione-trasparente",
        "organizzazione",
        "organigramma",
        "dirigenti",
        "vertice",
        "organi-di-governo",
        "organi-di-indirizzo-politico-amministrativo",
        "incarichi-amministrativi-di-vertice",
    ],
    "page_family_terms": {
        "contact": ["contatti", "segreteria"],
        "directory": ["rubrica", "personale", "docenti", "strutture", "ruoli"],
        "office": ["ufficio", "uffici", "segreteria", "servizi"],
        "governance": [
            "amministrazione-trasparente",
            "organizzazione",
            "organigramma",
            "dirigenti",
            "vertice",
            "organi-di-governo",
            "organi-di-indirizzo-politico-amministrativo",
        ],
        "international": [
            "internazionale",
            "internazionalizzazione",
            "mobilita",
            "erasmus",
            "relazioni-internazionali",
            "cooperazione-internazionale",
        ],
        "staff": ["personale", "docenti", "team"],
    },
    "negative_terms": [
        "privacy",
        "cookie",
        "eventi",
        "notizie",
        "alumni",
    ],
    "slug_hints": [
        "/contatti",
        "/contatti-uffici",
        "/rubrica",
        "/uffici",
        "/ufficio-erasmus",
        "/erasmus",
        "/internazionale",
        "/internazionalizzazione",
        "/mobilita",
        "/mobilita-internazionale",
        "/relazioni-internazionali",
        "/cooperazione-internazionale",
        "/organigramma",
        "/personale",
        "/docenti",
        "/amministrazione/contatti",
        "/segreteria",
        "/ufficio-relazioni-internazionali",
        "/contatti/erasmus",
        "/amministrazione-trasparente",
        "/amministrazione-trasparente-home",
        "/organizzazione",
        "/organizzazionemenu",
        "/dirigenti",
        "/vertice",
        "/organi-di-governo",
        "/organi-di-indirizzo-politico-amministrativo",
        "/incarichi-amministrativi-di-vertice",
        "/opportunita",
        "/it/contatti",
        "/it/rubrica",
        "/it/organizzazione",
        "/it/amministrazione-trasparente",
        "/it/amministrazione-trasparente-home",
        "/it/personale",
        "/it/dirigenti",
        "/it/vertice",
        "/it/opportunita",
    ],
}


ITALY_CONTACT_PACK = {
    "name_particles": [
        "dal",
        "della",
        "di",
    ],
    "name_stopwords": [
        "accoglienza",
        "amministrative",
        "amministrativi",
        "amministrativo",
        "assistenza",
        "ateneo",
        "consulta",
        "didattica",
        "direttore",
        "direzione",
        "economato",
        "internazionale",
        "internazionali",
        "italiana",
        "italiane",
        "italiano",
        "lingua",
        "lingue",
        "orientamento",
        "palazzo",
        "parlate",
        "piazza",
        "protocollo",
        "pubblico",
        "ragioneria",
        "responsabile",
        "rettorato",
        "sede",
        "segreteria",
        "settore",
        "sportello",
        "uffici",
        "ufficio",
        "universita",
        "via",
        "viale",
    ],
    "address_terms": [
        "casale",
        "corso",
        "largo",
        "padova",
        "padua",
        "palazzo",
        "piazza",
        "via",
        "viale",
    ],
    "address_like_phrases": [
        "casale di",
        "via del",
        "via della",
        "via di",
    ],
    "office_name_terms": [
        "amministrativa",
        "amministrativo",
        "biblioteca",
        "consulta",
        "didattica",
        "direttore",
        "direzione",
        "economato",
        "palazzo",
        "protocollo",
        "ragioneria",
        "settore",
        "sportello",
        "uffici",
        "ufficio",
    ],
    "boilerplate_name_fragments": [
        "consulta studenti",
        "direttore di ragioneria",
        "direzione amministrativa",
        "sede didattica",
        "sportello on line",
        "sportello on-line",
    ],
    "office_role_terms": [
        "uffici",
        "ufficio",
    ],
    "role_signal_terms": [
        "cooperazione internazionale",
        "internazionale",
        "internazionali",
        "mobilita",
        "relazioni internazionali",
        "studenti internazionali",
    ],
    "role_aliases": {
        "international admissions": [
            "ammissione internazionale",
            "ammissioni internazionali",
        ],
        "international office": [
            "ufficio internazionale",
            "ufficio internazionalizzazione",
        ],
        "international mobility": [
            "mobilita",
        ],
        "international partnerships": [
            "cooperazione internazionale",
            "cooperazione",
        ],
        "international relations": [
            "relazioni internazionali",
        ],
        "international student office": [
            "studenti internazionali",
        ],
    },
    "international_markers": [
        "internazionale",
        "internazionali",
    ],
    "office_markers": [
        "segreteria",
        "sportello",
        "uffici",
        "ufficio",
    ],
    "admissions_markers": [
        "ammissione",
        "ammissioni",
    ],
    "relevant_mailbox_terms": [
        "cooperazione",
        "internazionale",
        "mobilita",
        "relazioni",
    ],
    "irrelevant_mailbox_terms": [
        "alloggi",
        "biblioteca",
        "consulta",
        "contabil",
        "didatt",
        "economato",
        "protocollo",
        "ragioneria",
        "studenti",
        "stampa",
    ],
    "suspicious_name_phrases": [
        "casale di",
        "consulta studenti",
        "direttore di ragioneria",
        "direzione amministrativa",
        "il conservatorio",
        "sede didattica",
        "sportello on line",
        "sportello on-line",
    ],
    "suspicious_name_terms": [
        "accademia",
        "ateneo",
        "biblioteca",
        "consulta",
        "conservatorio",
        "didattica",
        "direttore",
        "direzione",
        "economato",
        "istituto",
        "protocollo",
        "ragioneria",
        "segreteria",
        "sportello",
        "studenti",
        "ufficio",
        "universita",
    ],
    "relevant_office_role_terms": [
        "cooperazione internazionale",
        "erasmus",
        "mobilita internazionale",
        "relazioni internazionali",
        "ufficio internazionale",
        "welcome office",
    ],
    "senior_role_terms": [
        "delegato del rettore",
        "direttore",
        "direttore amministrativo",
        "direttore generale",
        "presidente",
        "prorettore",
        "referente",
        "responsabile",
        "rettore",
        "vice direttore",
        "vicedirettore",
    ],
    "international_leadership_terms": [
        "coordinatore erasmus",
        "coordinatore internazionale",
        "coordinatore mobilita",
        "delegato all'internazionalizzazione",
        "delegato erasmus",
        "direttore relazioni internazionali",
        "head of international",
        "referente erasmus",
        "referente internazionale",
        "responsabile mobilita internazionale",
        "responsabile relazioni internazionali",
        "ufficio relazioni internazionali",
    ],
    "role_holder_page_terms": [
        "amministrazione trasparente",
        "contatti",
        "dirigenti",
        "docenti",
        "organigramma",
        "organizzazione",
        "personale",
        "rettorato",
        "rubrica",
        "uffici",
        "ufficio",
        "vertice",
    ],
    "person_name_titles": [
        "amb",
        "avv",
        "dott",
        "dottoressa",
        "dottore",
        "ing",
        "professoressa",
        "professore",
        "sig",
        "sigra",
        "signor",
        "signora",
        "ssa",
    ],
    "enrichment_block_phrases": [
        "amministrazione trasparente",
        "bienni musicoterapia",
        "dottorati di ricerca",
        "organizzazione interna",
        "personale tecnico",
        "richiedi info",
        "sant'anna magazine",
    ],
    "enrichment_block_terms": [
        "amministrazione",
        "bienni",
        "dottorati",
        "organizzazione",
        "personale",
        "ricerca",
        "richiedi",
        "studi",
        "tecnico",
        "trasparente",
    ],
}
